version: '3'

services:
  ldap-server:
    build: ./openldap
    container_name: ldap-host
    restart: always
    environment:
      LDAP_ORGANISATION: "example"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "password"
    ports:
      - "10389:389"

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap-server:ldap"

  redmine:
    image: redmine:5.0.3
    container_name: test1-redmine
    restart: always
    ports:
      - "13000:3000"
    links:
      - "ldap-server:ldap"

  gitlab:
    build: ./gitlab
    container_name: cicd-gitlab
    hostname: 'localhost'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 433
    ports:
      - '80:80'
      - '433:433'
    links:
      - "ldap-server:ldap"
  # CI Management
  jenkins:
    image: jenkins:2.60.3
    container_name: cicd-jenkins
    restart: always
    ports:
      - '18080:8080'
      - '50000:50000'
    links:
      - "ldap-server:ldap"

 # Quality Management(& Report)
  sonarqube:
    build: 
      context: ./sonarqube
      dockerfile: Dockerfile
    container_name: cicd-sonarqube
    restart: always
    ports:
      - '19000:9000'
    links:
      - "ldap-server:ldap"